export const DataType = {
  String: "string",
  Number: "number",
  Integer: "integer",
  Float: "float",
  Boolean: "boolean",
  Object: "object",
  ArrayString: "array_string",
  ArrayNumber: "array_number",
  ArrayBoolean: "array_boolean",
  ArrayObject: "array_object",
}

export const FieldType = {
  Text: "text",
  Password: "password",
  Email: "email",
  Number: "number",
  Date: "data",
  Checkbox: "checkbox",
  Labels: "labels",
  KeyValueMap: "key_value_map",
  ThresholdsColor: "thresholds_color",
  Divider: "divider",
  Select: "select",
  SelectTypeAhead: "select_type_ahead",
  SelectTypeAheadMultiple: "select_type_ahead_multiple",
  SelectTypeAheadAsync: "select_type_ahead_async",
  Switch: "switch",
}
