export const DataType = {
  String: "string",
  Number: "number",
  Integer: "integer",
  Float: "float",
  Boolean: "boolean",
  Object: "object",
  ArrayString: "array_string",
  ArrayNumber: "array_number",
  ArrayBoolean: "array_boolean",
  ArrayObject: "array_object",
}

export const FieldType = {
  Text: "text",
  Password: "password",
  Email: "email",
  Number: "number",
  Date: "data",
  Checkbox: "checkbox",
  Labels: "labels",
  KeyValueMap: "key_value_map",
  VariablesMap: "variables_map",
  ThresholdsColor: "thresholds_color",
  DynamicArray: "dynamic_array",
  ConditionsArrayMap: "conditions_array_map",
  Divider: "divider",
  Select: "select",
  SelectTypeAhead: "select_type_ahead",
  SelectTypeAheadMultiple: "select_type_ahead_multiple",
  SelectTypeAheadAsync: "select_type_ahead_async",
  Switch: "switch",
  DatePicker: "date_picker",
  DateRangePicker: "date_range_picker",
  TimePicker: "time_picker",
  TimeRangePicker: "time_range_picker",
  ToggleButtonGroup: "toggle_button_group",
  ScriptEditor: "script_editor",
}
